title: Mindi Kessenich Real Estate and Design
email: hello@mindikessenich.com
description: Madison, WI Real Estate and Design
baseurl: ""
url: "https://mindikessenich.com"

lang: en_US
timezone: America/Chicago

markdown: kramdown
permalink: /:categories/:title/

author:
  name: Mindi Kessenich
  short_name: Mindi
  email: mindi@exithgm.net

logo: /assets/images/logo-banner-580x200.png

facebook:
  publisher: mindikessenichrealestateanddesign

social:
  name: Mindi Kessenich Real Estate and Design
  links:
    - https://www.facebook.com/mindikessenichrealestateanddesign
    - https://www.instagram.com/mkrealestateanddesign/

webmaster_verifications:
  google: SykVDNd9WMgHu7KJNGfHoTuFyVImq7Of8605j8KV4B4

paginate: 5
paginate_path: "/blog/:num/"

sass:
  sass_dir: assets/_sass
  style: compressed

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      author: mindi_kessenich

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-seo-tag

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
